version: "3"

services:
  web:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    ports:
      - 3000:8000
    command: python manage.py runserver 0:8000

  postgres:
    image: postgres:15
    # Creation of environment inside container
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - database:/data/db
    ports:
      - 27017:5432

volumes:
  database:
